---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library("tidyverse")
```

# Import Data

```{r}
secret_url <- read_csv("data/secret-url.csv")
patristics_data <- read_csv(secret_url[[1]])
```

```{r}
colnames(patristics_data) <- make.names(colnames(patristics_data))

gg_jen <- patristics_data %>% 
  group_by(Epistle, Early.Christian.Writer) %>%
  mutate(how.many = n()) %>%
  select(how.many) %>%
  unique() %>%
  ggplot() + geom_bar(aes(x = Epistle, y = how.many, fill = Early.Christian.Writer),stat = "identity") + coord_flip()


gg_jen
```

```{r}
library(plotly)

library(highcharter)

patristics_data %>% 
  group_by(Epistle, Early.Christian.Writer) %>%
  mutate(how.many = n()) %>%
  select(how.many) %>%
  unique() %>%
  hchart(
    type = "bar",
    hcaes(
      x = Epistle, y = how.many, 
      group = Early.Christian.Writer
    )
  ) %>%
  hc_plotOptions(series = list(stacking = "stack"))
```

```{r}
patristics_data %>% 
  group_by(Epistle, Early.Christian.Writer) %>%
  mutate(how.many = n()) %>%
  select(how.many) %>%
  unique() %>%
  hchart(
    type = "bar",
    hcaes(
      x = Epistle, y = how.many, 
      group = Early.Christian.Writer
    )
  ) %>%
  hc_plotOptions(series = list(stacking = "percent")) %>%
  hc_tooltip(shared = TRUE)
```


# Network Visualisation

```{r}
patristics_data %>%
  # filter(Epistle == "1 Corinthians") %>%
  # filter(StartVerse == "2:9") %>%
  group_by(Early.Christian.Writer, Epistle) %>%
  select(Early.Christian.Writer, Epistle) %>%
  unique()
```

